In [ ]:

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from random import sample
from sklearn.linear_model import LogisticRegression
from sklearn import tree
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn import preprocessing
from IPython.display import Image  
from pydotplus import graph_from_dot_data

from sklearn.linear_model import LogisticRegression
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import GridSearchCV


In [ ]:
import numpy as np
import pandas as pd

In [ ]:

df = pd.read_csv('/content/drive/My Drive/HunterDouglas-DummyEncoded.2.csv')


In [ ]:
df1 = df.copy()


In [ ]:
df2 = df.copy() #df2 is REP
df3 = df.copy() #df3 is REM

In [ ]:
del df1 ['REM_Order']
del df1 ['REP_Order']

In [ ]:
del df2 ['flagged_Order']
del df2 ['REM_Order']

In [ ]:
del df3 ['flagged_Order']

In [ ]:
del df3 ['REP_Order']

In [ ]:
del df1['combinedLines']
del df2['combinedLines']
del df3['combinedLines']
del df1['combinedSalesLines']
del df2['combinedSalesLines']
del df3['combinedSalesLines']
del df1['OPERATING_SYS_OPT_ID']
del df2['OPERATING_SYS_OPT_ID']
del df3['OPERATING_SYS_OPT_ID']
del df1['Area']
del df2['Area']
del df3['Area']
del df1['REGIONAL_SALES_MGR_ID']
del df2['REGIONAL_SALES_MGR_ID']
del df3['REGIONAL_SALES_MGR_ID']

In [ ]:
df2.head()
df2['REGION_STATE_ID'] = df2['REGION_STATE_ID'].astype(object)
df2['FABRIC_ID'] = df2['FABRIC_ID'].astype(object)
df2['HEIGHT'] = df2['HEIGHT'].astype(object)
df2['COLOR_ID'] = df2['COLOR_ID'].astype(object)
df2['ORIGINAL_MATERIAL_ID'] = df2['ORIGINAL_MATERIAL_ID'].astype(object)
df2['OPERATING_SYSTEM_ID'] = df2['OPERATING_SYSTEM_ID'].astype(object)
df2['Day'] = df2['Day'].astype(object)
df2['Month'] = df2['Month'].astype(object)



In [ ]:
df3.head()
df3['REGION_STATE_ID'] = df3['REGION_STATE_ID'].astype(object)
df3['FABRIC_ID'] = df3['FABRIC_ID'].astype(object)
df3['HEIGHT'] = df3['HEIGHT'].astype(object)
df3['COLOR_ID'] = df3['COLOR_ID'].astype(object)
df3['ORIGINAL_MATERIAL_ID'] = df3['ORIGINAL_MATERIAL_ID'].astype(object)
df3['OPERATING_SYSTEM_ID'] = df3['OPERATING_SYSTEM_ID'].astype(object)
df3['Day'] = df3['Day'].astype(object)
df3['Month'] = df3['Month'].astype(object)

In [ ]:


# Randomly, split the data into test/training/validation sets
train, test, validate = np.split(df2.sample(frac=1), [int(.6*len(df1)), int(.8*len(df1))])
print (train.shape, test.shape, validate.shape)
# (8999, 20) (3000, 20) (3000, 20)

# Separate target and predictors
y_train = train['REP_Order']
x_train = train.drop(['REP_Order'], axis=1)
y_test = test['REP_Order']
x_test = test.drop(['REP_Order'], axis=1)
y_validate = validate['REP_Order']
x_validate = validate.drop(['REP_Order'], axis=1)

# Check the balance of the splits on y_
y_test.mean()

y_train.mean()







(458546, 13) (152849, 13) (152849, 13)


0.0032101468554954138

In [ ]:
y_test.mean()

0.003238490274715569

In [ ]:
y_train.mean()

0.0032101468554954138

In [ ]:
rf = RandomForestClassifier()
rf.fit(x_train, y_train)
print ("Features sorted by their score:")
print (sorted(zip(map(lambda x: round(x, 4), rf.feature_importances_), x_train), reverse=True))


Features sorted by their score:
[(0.1956, 'FABRIC_ID'), (0.1813, 'COLOR_ID'), (0.138, 'WIDTH'), (0.1252, 'HEIGHT'), (0.1032, 'Day'), (0.0945, 'REGION_STATE_ID'), (0.0745, 'Month'), (0.0547, 'ORIGINAL_MATERIAL_ID'), (0.0239, 'OPERATING_SYSTEM_ID'), (0.0049, 'USA'), (0.0043, 'Canada'), (0.0, 'Year')]


In [ ]:
all_vars = x_train.columns.tolist()
top_6_vars = ['WIDTH', 'HEIGHT', 'DAY', 'COLOR_ID', 'MONTH','FABRIC_ID','Day','Month','ORIGINAL_MATERIAL_ID','OPERATING_SYSTEM_ID']
bottom_vars = [cols for cols in all_vars if cols not in top_6_vars]

#Drop less important variables leaving the top_6
x_train    = x_train.drop(bottom_vars, axis=1)
x_test     = x_test.drop(bottom_vars, axis=1)
x_validate = x_validate.drop(bottom_vars, axis=1)

In [ ]:
#scaler = StandardScaler()
#x_train = scaler.fit_transform(x_train)
#x_test = scaler.fit_transform(x_test)
#x_validate = scaler.fit_transform(x_validate)

In [ ]:
# Instantiate
logit_model = LogisticRegression(random_state = 0, class_weight='balanced', max_iter=100000)
# Fit
logit_model = logit_model.fit(x_train, y_train)
# How accurate?
logit_model.score(x_train, y_train)
#0.7874

# How does it perform on the test dataset?

# Predictions on the test dataset
predicted = pd.DataFrame(logit_model.predict(x_test))
# Probabilities on the test dataset
probs = pd.DataFrame(logit_model.predict_proba(x_test))
print (metrics.accuracy_score(y_test, predicted))


0.642994066039032


In [ ]:
print (metrics.confusion_matrix(y_test, predicted))
print (metrics.classification_report(y_test, predicted))

[[97968 54386]
 [  182   313]]
              precision    recall  f1-score   support

           0       1.00      0.64      0.78    152354
           1       0.01      0.63      0.01       495

    accuracy                           0.64    152849
   macro avg       0.50      0.64      0.40    152849
weighted avg       0.99      0.64      0.78    152849



In [ ]:
penalty = ['l2']
C = np.logspace(0, 4, 10)
hyperparameters = dict(C=C, penalty=penalty)

In [ ]:
lr = LogisticRegression(random_state = 0,class_weight='balanced', max_iter=100000)
clf = GridSearchCV(lr, hyperparameters, cv=5, verbose=0, scoring='recall')

In [ ]:
best_model = clf.fit(x_train, y_train)
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', round(best_model.best_estimator_.get_params()['C'],2))

Best Penalty: l2
Best C: 7.74


In [ ]:
y_pred_gs = pd.DataFrame(best_model.predict(x_test))
y_probs_gs = pd.DataFrame(best_model.predict_proba(x_test))

In [ ]:
print (metrics.accuracy_score(y_test, y_pred_gs ))

0.6682215781588365


In [ ]:
print (metrics.confusion_matrix(y_test, y_pred_gs))
print (metrics.classification_report(y_test, y_pred_gs))

[[101836  50518]
 [   194    301]]
              precision    recall  f1-score   support

           0       1.00      0.67      0.80    152354
           1       0.01      0.61      0.01       495

    accuracy                           0.67    152849
   macro avg       0.50      0.64      0.41    152849
weighted avg       0.99      0.67      0.80    152849



In [ ]:

# Randomly, split the data into test/training/validation sets
train, test, validate = np.split(df3.sample(frac=1), [int(.6*len(df2)), int(.8*len(df2))])
print (train.shape, test.shape, validate.shape)
# (8999, 20) (3000, 20) (3000, 20)

# Separate target and predictors
y_train = train['REM_Order']
x_train = train.drop(['REM_Order'], axis=1)
y_test = test['REM_Order']
x_test = test.drop(['REM_Order'], axis=1)
y_validate = validate['REM_Order']
x_validate = validate.drop(['REM_Order'], axis=1)

# Check the balance of the splits on y_
y_test.mean()

y_train.mean()






(458546, 13) (152849, 13) (152849, 13)


0.05412325044815569

In [ ]:
y_test.mean()

0.05453094230253387

In [ ]:
y_train.mean()

0.05412325044815569

In [ ]:
# Instantiate
logit_model = LogisticRegression(random_state = 0,class_weight='balanced', max_iter=100000)
# Fit
logit_model = logit_model.fit(x_train, y_train)
# How accurate?
logit_model.score(x_train, y_train)
#0.7874

# How does it perform on the test dataset?

# Predictions on the test dataset
predicted = pd.DataFrame(logit_model.predict(x_test))
# Probabilities on the test dataset
probs = pd.DataFrame(logit_model.predict_proba(x_test))
print (metrics.accuracy_score(y_test, predicted))

0.6103736367264424


In [ ]:
probs

0         1
0       0.198423  0.801577
1       0.630243  0.369757
2       0.613465  0.386535
3       0.291028  0.708972
4       0.313812  0.686188
...          ...       ...
152844  0.382293  0.617707
152845  0.614940  0.385060
152846  0.466351  0.533649
152847  0.567492  0.432508
152848  0.676487  0.323513

[152849 rows x 2 columns]

In [ ]:
print (metrics.confusion_matrix(y_test, predicted))
print (metrics.classification_report(y_test, predicted))

[[88629 55885]
 [ 3669  4666]]
              precision    recall  f1-score   support

           0       0.96      0.61      0.75    144514
           1       0.08      0.56      0.14      8335

    accuracy                           0.61    152849
   macro avg       0.52      0.59      0.44    152849
weighted avg       0.91      0.61      0.72    152849

